---
- hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Enable Nginx Service
      service:
         name: nginx
         state: started
    