name: CD

on: [ workflow_dispatch ]

jobs:

  terraform:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.2.7
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Validate Terraform Module
        run: |
          terraform validate

      - name: Plan Terraform Destory
        id: plan
        run: |
          terraform plan -destroy -var-file dev.tfvars -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan   

      - name: Destory Terraform
        id: apply
        continue-on-error: true
        run: |
          terraform apply -input=false -no-color tfplan