name: CD

on:
  push:
    branches:
      - main

jobs:
  path_filter:
    runs-on: ubuntu-20.04
    outputs:
      run_packer: ${{ steps.filter.outputs.packer }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          packer:
            - 'packer/**'

  packer:
    runs-on: ubuntu-20.04
    if: needs.path_filter.outputs.run_packer == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - \
          && sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
          && sudo apt-get update && sudo apt-get install packer

      - name: Init Packer
        run: |
          packer init packer/

      # validate templates
      - name: Build Template
        run: |
          packer build packer/nginx_ami.pkr.hcl

  terraform:
    runs-on: ubuntu-20.04
    needs: packer
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.2.7
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Validate Terraform Module
        run: |
          terraform validate

      - name: Plan Terraform
        id: plan
        run: |
          terraform plan -var-file dev.tfvars -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan   

      - name: Apply Terraform
        id: apply
        continue-on-error: true
        run: |
          terraform apply -input=false -no-color tfplan